### ISSUE TITLE
attempt to send more than one response for command launch

### ISSUE THREAD

**Issue by naquiroz** [facebook-atom/atom-ide-debugger-python#7]
I'm getting an error when attempting to launch python debugger.
> attempt to send more than one response for command launch

What am I doing wrong?

![image](https://user-images.githubusercontent.com/29825816/43610865-65a2a98a-9675-11e8-82be-a5169092fbf3.png)

**Comment by james-rappazzo** [comment]
getting the same issue

**Comment by Goom11** [comment]
@naquiroz and @james-rappazzo , I have noticed this issue recently. Can you both confirm for me, does this error message break debugging in any way or is it just adding to a message to the console?

**Comment by james-rappazzo** [comment]
@Goom11 it doesn't seem to break anything, just an error message as far as I can tell.

**Comment by naquiroz** [comment]
@Goom11 in my case it does break it.

**Comment by Ignus3** [comment]
Having the same issue as well, does not seem to break anything for me. Maybe something to do with Nuclide debugger + python debugger? Messages are being sent by 2 different debuggers. (error from python, process exited from nuclide)

**Comment by Goom11** [comment]
@naquiroz , is there a specific repro you can give me? I am seeing this but it isn't preventing me from debugging.

**Comment by TrilceAC** [comment]
I am developing a Flask web application and seeing this error. It might well be that I'm new to atom, but in my case the issue is that any breakpoint out of the script that has the run is just ignored. When I launch the server, the breakpoints at my "run.py" are effective: I can go step pby step and so on, but once I continue I am not able to track any request because the breakpoints are ignored.

**Comment by Goom11** [comment]
This has now been fixed here: https://github.com/facebook/nuclide/commit/90629ee9fded9fb1f8dc761b827bfddbb19aeeb1.

I suspect though that if this issue was actually preventing debugging for you, then this fix will not fix debugging for you, it will simply remove the message. If debugging still doesn't work, open a new issue and give me a repro and I will look into it :)
